# This is a basic workflow to help you get started with Actions

name: fetch-data

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */4 * * *' 
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install python dependencies
        run: pip install -r ./requirements.txt --upgrade pip
      
      # Runs a single command using the runners shell
      - name: Run a python data scraper, writing data to /src/data.json
        run: python ./scraper.py
        
      # Prints fetched data
      - name: Print fetchd data
        run: cat ./src/data.json
      
      # Runs a set of commands using the runners shell
      - name: Commit new data
        run: |
          git config --global user.name 'sam-bauer'
          git config --global user.email 'sam-bauer@users.noreply.github.com'
          git commit -am "Automated data update" 
          git push
